name: Python package

on: [push, pull_request]

jobs:
  build:
    env:
      CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Create remote .secrets file
        shell: bash
        run: |
          echo census_api_key=\"$CENSUS_API_KEY\" >> .secrets.toml
          cat .secrets.toml
      - name: Run tox
        run: |
          tox
      - name: Delete .secrets file
        run: |
          rm .secrets.toml
        shell: bash
