name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Decode base64 secrets
        run: echo $SECRETS_FILE_CONTENTS | base64 -d > .secrets.toml
        env:
          SECRETS_FILE_CONTENTS: ${{ secrets.CENSUS_API_KEY }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox
        run: |
          tox
